# Generated by Django 6.0 on 2026-01-21 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bulkrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='rating',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
