# Generated by Django 6.0 on 2026-02-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bulkrequest_status_alter_bulkrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='available_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='total_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
