# Generated by Django 3.2.23 on 2026-02-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_contractorprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkrequest',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractorprofile'),
        ),
        migrations.AlterField(
            model_name='bulkrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='available_workers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='total_workers',
            field=models.IntegerField(),
        ),
    ]
