# Generated by Django 3.2.23 on 2026-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bulkrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
