# Generated by Django 3.2.23 on 2026-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20260205_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
