# Generated by Django 3.2.23 on 2026-02-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260207_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bulkrequest')),
            ],
        ),
    ]
