# Generated by Django 3.2.23 on 2026-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bulkfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
