# Generated by Django 3.2.23 on 2026-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260208_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
