# Generated by Django 3.2.23 on 2026-02-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20260208_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulkFeedback',
            new_name='BulkReview',
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Review',
        ),
    ]
