# Generated by Django 3.2.23 on 2026-02-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20260208_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='projects_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='success_rate',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='success_rate',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
