# Generated by Django 3.2.23 on 2026-02-08 17:31

from django.db import migrations


def add_services(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    services = [
        ('Tiles Worker', 'tiles-worker', 'TW', 'Tile installation and repair'),
        ('Demolition Worker', 'demolition-worker', 'DW', 'Safe demolition and debris removal'),
        ('Waterproofing Worker', 'waterproofing-worker', 'WP', 'Leakage and dampness solutions'),
        ('Welder', 'welder', 'W', 'Metal fabrication and welding'),
        ('Event Decorator', 'event-decorator', 'ED', 'Decorations for all occasions'),
        ('Stage Setup Worker', 'stage-setup-worker', 'SS', 'Professional stage construction'),
        ('Lighting Technician', 'lighting-technician', 'LT', 'Event and industrial lighting'),
        ('Bouncer', 'bouncer', 'B', 'Event and personal security'),
        ('Driver on Hire', 'driver-on-hire', 'DH', 'Experienced drivers for all vehicles'),
        ('Car Wash', 'car-wash', 'CW', 'Premium doorstep car cleaning'),
        ('Bike Wash', 'bike-wash', 'BK', 'Quality doorstep bike cleaning'),
        ('Cook', 'cook', 'CK', 'Home and event cooking services'),
        ('Household Helper', 'household-helper', 'HH', 'Help with daily household chores'),
        ('Water Tank Cleaning', 'water-tank-cleaning', 'WT', 'Hygienic water tank cleaning'),
        ('Home Organizer', 'home-organizer', 'HO', 'Decluttering and organization'),
        ('Gardener', 'gardener', 'G', 'Lawn care and landscaping'),
        ('Pest Control Worker', 'pest-control-worker', 'PC', 'Effective pest management'),
        ('Packers & Movers Helper', 'packers-movers-helper', 'PM', 'Help with packing and moving'),
        ('Warehouse Labour', 'warehouse-labour', 'WH', 'Skilled warehouse operations help'),
        ('Loading/Unloading Worker', 'loading-unloading-worker', 'LU', 'Efficient heavy lifting and loading'),
    ]
    for name, slug, icon, desc in services:
        Service.objects.get_or_create(
            name=name,
            slug=slug,
            defaults={'icon': icon, 'desc': desc}
        )

def remove_services(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    slugs = [
        'tiles-worker', 'demolition-worker', 'waterproofing-worker', 'welder',
        'event-decorator', 'stage-setup-worker', 'lighting-technician', 'bouncer',
        'driver-on-hire', 'car-wash', 'bike-wash', 'cook', 'household-helper',
        'water-tank-cleaning', 'home-organizer', 'gardener', 'pest-control-worker',
        'packers-movers-helper', 'warehouse-labour', 'loading-unloading-worker',
    ]
    Service.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20260208_1735'),
    ]

    operations = [
        migrations.RunPython(add_services, remove_services),
    ]
