# Generated by Django 3.2.23 on 2026-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_new_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bulkrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bulkrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bulkrequest',
            name='strategic_notes',
            field=models.TextField(blank=True),
        ),
    ]
