# Generated by Django 6.0.1 on 2026-03-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
