# Generated by Django 6.0.1 on 2026-03-15 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Hire',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='booking',
            new_name='hire',
        ),
    ]
