# Generated by Django 3.2.23 on 2026-05-12 12:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_booking_hire_rename_booking_review_hire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, validators=[core.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='bulkrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='hire',
            name='name',
            field=models.CharField(blank=True, max_length=100, validators=[core.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='hire',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=10, validators=[core.validators.validate_phone]),
        ),
    ]
