# Generated by Django 3.2.23 on 2026-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20260512_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='time_slot',
            field=models.CharField(choices=[('08-10', '08:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('12-14', '12:00 PM - 02:00 PM'), ('14-16', '02:00 PM - 04:00 PM'), ('16-18', '04:00 PM - 06:00 PM'), ('18-20', '06:00 PM - 08:00 PM')], default='Morning', max_length=20),
        ),
    ]
