# Generated by Django 3.2.23 on 2026-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_hire_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkrequest',
            name='time_slot',
            field=models.CharField(choices=[('08-10', '08:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('12-14', '12:00 PM - 02:00 PM'), ('14-16', '02:00 PM - 04:00 PM'), ('16-18', '04:00 PM - 06:00 PM'), ('18-20', '06:00 PM - 08:00 PM')], default='08-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkrequest',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hire',
            name='time_slot',
            field=models.CharField(choices=[('08-10', '08:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('12-14', '12:00 PM - 02:00 PM'), ('14-16', '02:00 PM - 04:00 PM'), ('16-18', '04:00 PM - 06:00 PM'), ('18-20', '06:00 PM - 08:00 PM')], default='08-10', max_length=20),
        ),
    ]
