# Generated by Django 3.2.23 on 2026-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20260512_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkrequest',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
